eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,env

logging:
  level:
    root: INFO

jwt:
  secret: change-this-secret-key-change-this-secret-key
  expiration-ms: 86400000
