spring:
  application:
    name: backend.service-discovery
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost

logging:
  level:
    com.netflix.eureka: INFO
